### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by bbslzy001** [bbslzy001/money-minder#3]
### 描述
打开 `http://127.0.0.1:8080/tool/manage-bill` 页面时报错如下：

> Uncaught runtime errors:
ERROR
ResizeObserver loop limit exceeded
    at handleError (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:299:58)
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:318:7)

### 解决方法
在main.ts中定义如下内容：
```
type DebounceFunction = (...args: any[]) => void;

const debounce = (fn: DebounceFunction, delay: number): DebounceFunction => {
    let timer: number | null = null;
    return function (this: ThisParameterType<DebounceFunction>, ...args: any[]): void {
        const context = this;
        clearTimeout(timer as number | undefined);
        timer = window.setTimeout(function (this: ThisParameterType<DebounceFunction>) {
            fn.apply(context, args);
        }, delay);
    };
};

const _ResizeObserver = window.ResizeObserver;
window.ResizeObserver = class ResizeObserver extends _ResizeObserver {
    constructor(callback: (entries: ResizeObserverEntry[], observer: ResizeObserver) => void) {
        const debouncedCallback = debounce(callback, 16);
        super(debouncedCallback);
    }
};
```

**Comment by bbslzy001** [comment]
解决方案如下：
https://github.com/element-plus/element-plus/issues/10630
